### ISSUE TITLE
Some more info on (updated) prerequisites

### ISSUE THREAD

**Issue by AlexStragies** [VulpesSARL/MiniNT5-Tools#1]
Hello, thank you for creating this interesting project.

Could you please detail some more things in the README:

- Will more recent versions of the ADK and the platform toolset also be supported?
- Have you tried other versions of VS or other IDEs to build the project?
- Will this support the unified .Net 2019+?
- What are the administrator rights needed for?
- Could you perhaps add some more info about the "Fox*" components?

**Comment by VulpesSARL** [comment]
README.md updated! (https://github.com/VulpesSARL/MiniNT5-Tools/commit/af960b61b77d7dcfd1bd0cc5f428ab23a85c7dad)
